---
title: "Evaluating weighted regression half-window widths"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---
  
```{r, warning = F, message = F, echo = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F)

library(shiny)
library(tidyverse)
library(lubridate)
library(WtRegDO)
library(patchwork)
library(ShinyDash)
library(shinydashboard)
library(flexdashboard)
library(RColorBrewer)
```

```{r reactives}
# metab observed data 
metobsdat <- reactive({
  
  # inputs
  site <- input$site
  dts <- input$dts
  day <- input$day
  hour <- input$hour
  tide <- input$tide
    
  flnm <- paste('metobs', site, day, hour, tide, sep = '_')
  load(file = paste0('data/', flnm, '.RData'))
  dat <- get(flnm) %>% 
    na.omit()
 
  # get year
  yr <- dat$Date %>% 
    strftime(format = '%Y') %>% 
    unique
  dts <- ymd(paste0(yr, '-1-1')) + dts - 1
    
  # filter
  out <- dat %>% 
    filter(Date >= dts[1] & Date <= dts[2])

  attr(out, 'rawdat') <- attr(out, 'rawdat') %>% 
    filter(DateTimeStamp >= dts[1] & DateTimeStamp <= dts[2])
  
  return(out)
  
})
  
# metab detided data 
metdtddat <- reactive({
  
  # inputs
  site <- input$site
  dts <- input$dts
  day <- input$day
  hour <- input$hour
  tide <- input$tide

  flnm <- paste('metdtd', site, day, hour, tide, sep = '_')
  load(file = paste0('data/', flnm, '.RData'))
  dat <- get(flnm) %>% 
    na.omit()
  
  # get year
  yr <- dat$Date %>% 
    strftime(format = '%Y') %>% 
    unique
  dts <- ymd(paste0(yr, '-1-1')) + dts - 1
  
  # filter
  out <- dat %>% 
    filter(Date >= dts[1] & Date <= dts[2])
  
  attr(out, 'rawdat') <- attr(out, 'rawdat') %>% 
    filter(DateTimeStamp >= dts[1] & DateTimeStamp <= dts[2])
  
  return(out)
  
})
  
# obsserved data
obsdat <- reactive({
  
  # inputs
  site <- input$site
  dts <- input$dts
  day <- input$day
  hour <- input$hour
  tide <- input$tide
  
  flnm <- paste('DO', site, day, hour, tide, sep = '_')
  load(file = paste0('data/', flnm, '.RData'))
  dat <- get(flnm)

  # get year
  yr <- dat$Date %>% 
    strftime(format = '%Y') %>% 
    unique
  dts <- ymd(paste0(yr, '-1-1')) + dts - 1
    
  # filter
  out <- dat %>% 
    filter(DateTimeStamp >= dts[1] & DateTimeStamp <= dts[2])
  
  return(out)
  
})

# detided, observed eval data
evaldat <- reactive({
  
  # input
  metdtddat <- metdtddat()
  metobsdat <- metobsdat()

  evalobs <- meteval(metobsdat)
  evaldtd <- meteval(metdtddat)

  out <- list(Observed = evalobs, Detided = evaldtd)
  
  return(out)
  
})

# detided, observed correlation data
evalcorr <- reactive({
  
  # input
  evaldat <- evaldat()

  out <- evaldat %>% 
    enframe('set', 'corr') %>% 
    mutate(
      corr = purrr::map(corr, function(x){

        docorr <- x %>% 
          .[c('DOcor.month', 'DOcor.cor')] %>% 
          data.frame %>% 
          rename(month = DOcor.month, DOcor = DOcor.cor)
          
        metcorr <- x %>% 
          .[c('month', 'Pgcor', 'Rtcor')] %>% 
          data.frame 
        
        out <- full_join(docorr, metcorr, by = 'month') %>% 
          gather('var', 'val', -month)
        
        return(out)
      
      })
    ) %>% 
    unnest('corr') %>% 
    mutate(month = as.numeric(month)) %>% 
    mutate(
      month = factor(month, levels = sort(as.numeric(unique(month)))), 
      var = factor(var, levels = c('DOcor', 'Pgcor', 'Rtcor'), labels = c('DO', 'Pg', 'Rt')), 
      set = factor(set, levels = c('Observed', 'Detided'))
      )

  return(out)
  
})

# correlation plot
corplo <- reactive({

  # input
  evalcorr <- evalcorr()

  validate(
    need(nrow(evalcorr) > 0, "Insufficient data")
  )
  
  toplo <- evalcorr
  
  p <- ggplot(toplo, aes(x = month, y = val, group = set, colour = set)) + 
    geom_line() +
    geom_point() + 
    geom_hline(yintercept = 0, linetype = 'dashed') + 
    facet_grid( ~ var) + 
    scale_x_discrete(drop = F) + 
    scale_y_continuous(limits = c(-1, 1)) +
    ylab('Correlation with tide') +
    xlab('Month') +
    theme_bw() +
    theme(text = element_text(size=14), 
      legend.position = 'top',
      legend.direction = 'horizontal',
      legend.title = element_blank()
      )
  
  print(p)
  
  })

# beta estimate plots
betplo <- reactive({
  
  # input
  obsdat <- obsdat()
  dts <- input$dts

  req(obsdat)
  
  # format axis lims
  yr <- obsdat$DateTimeStamp %>% 
    strftime(format = '%Y') %>% 
    unique
  dts <- ymd(paste0(yr, '-1-1')) + dts - 1
  xlims <- dts
  
  out <- ggplot(obsdat, aes(x = DateTimeStamp, y = Beta2)) + 
    geom_line() + 
    geom_point(size = 0.5) +
    geom_hline(yintercept = 0, colour = 'tomato1') +
    labs(
      subtitle = expression(paste(italic('\u03B2'[2]), ' estimates of DO vs tidal height'))
      ) +
    scale_y_continuous(expression(italic('\u03B2'[2]))) +
    theme_bw() + 
    theme(
      axis.title.x = element_blank(),
      text = element_text(size=14) 
      ) +
    scale_x_datetime(limits = as.POSIXct(xlims))
  
  return(out)
  
})

# metabolism plot
metplo <- reactive({
  
  # input
  obsdat <- obsdat()
  metdtddat <- metdtddat()
  metobsdat <- metobsdat()
  dts <- input$dts
  
  validate(
    need(nrow(metdtddat) > 0, "Insufficient data")
  )

  # x axis limits
  # format axis lims
  yr <- obsdat$DateTimeStamp %>% 
    strftime(format = '%Y') %>% 
    unique
  dts <- ymd(paste0(yr, '-1-1')) + dts - 1
  xlims <- dts

  p1 <- plot(metobsdat, by = 'days') +
    labs(subtitle = 'Observed results') + 
    theme(legend.position = 'top') + 
    scale_x_date(limits = xlims)
  
  p2 <- plot(metdtddat, by = 'days') + 
    labs(subtitle = 'Detided results') + 
    theme(
      legend.position = 'none', 
      legend.title = element_blank()
      ) + 
    scale_x_date(limits = xlims)
  
  p1 + p2 + plot_layout(ncol = 1)
  
})

# dissolved oxygen and tidal height plot
dotdplo <- reactive({
  
  # input
  metobsdat <- metobsdat()
  obsdat <- obsdat()
  dts <- input$dts
  
  validate(
    need(nrow(obsdat) > 0, "Insufficient data")
  )

  # format axis lims
  yr <- obsdat$DateTimeStamp %>% 
    strftime(format = '%Y') %>% 
    unique
  dts <- ymd(paste0(yr, '-1-1')) + dts - 1

  # x axis limits
  yr <- metobsdat$Date %>% 
    year %>% 
    unique
  xlims <- dts
  
  toplo <- obsdat %>% 
    select(DateTimeStamp, DO_obs, DO_nrm) %>% 
    gather('var', 'val', -DateTimeStamp) %>% 
    mutate(var = factor(var, levels = c('DO_obs', 'DO_nrm'), labels = c('Observed', 'Detided')))
  
  p1 <- ggplot(toplo, aes(x = DateTimeStamp, y = val, colour = var)) + 
    geom_line() + 
    theme_bw() + 
    labs(y = 'DO (mg/l)', subtitle = '') +
    theme(
      legend.position = 'top', 
      legend.title = element_blank(), 
      axis.title.x = element_blank()
    ) + 
    scale_x_datetime(limits = as.POSIXct(xlims))
  
  p2 <- ggplot(obsdat, aes(x = DateTimeStamp, y = Tide, colour = Sal)) + 
    geom_line() + 
    theme_bw() + 
    scale_colour_gradientn(name = 'Sal (psu)', 
      colours = rev(brewer.pal(7, 'Spectral'))
      ) +
    labs(y = 'Tide (m)', subtitle = '') +
    theme(
      legend.position = 'top', 
      axis.title.x = element_blank()
    ) + 
    scale_x_datetime(limits = as.POSIXct(xlims))
  
  p1 + p2 + plot_layout(ncol = 1)
  
})

# anomalous table
anotab <- reactive({
  
  # input
  evaldat <- evaldat()

  out <- evaldat %>% 
    enframe('set', 'anom') %>% 
    mutate(
      anom = purrr::map(anom, function(x){

        out <- x %>% 
          .[c('meanPg', 'sdPg', 'anomPg', 'meanRt', 'sdRt', 'anomRt')] %>% 
          data.frame 
        
        names(out) <- c('Pg Mean', 'Pg SD', 'Pg Anom', 'Rt Mean', 'Rt SD', 'Rt Anom')
        
        return(out)
      
      })
    ) %>% 
    unnest('anom') %>% 
    mutate(
      set = factor(set, levels = c('Observed', 'Detided'))
      ) %>% 
    rename(Input = set) %>% 
    na.omit()

  validate(
    need(nrow(out) > 0, 'Insufficient data')
  )
  
  return(out)
  
})

# correlation table
cortab <- reactive({
  
  # input
  evalcorr <- evalcorr()
  
  validate(
    need(nrow(evalcorr) > 0, "Insufficient data")
  )
  
  out <- evalcorr %>% 
    spread(var, val) %>% 
    select(Month = month, Input = set, everything()) %>% 
    arrange(Month, Input) %>% 
    mutate(Month = ifelse(duplicated(Month), '', as.character(Month)))
  
  return(out)
  
})
```


Inputs {.sidebar data-width=400}
-------------------------------------

```{r ui}
column(12, 
  selectInput('site', label = 'Select site',  choices = list('Apalachicola 2019' = 'APNERR', 'Apalachicola 2018' = 'APNERR2018', 'Hudson River' = 'HUDNERR', 'Piermont' = 'PIERMO', 'Sapelo Island' = 'SAPDC'))
)
column(12, 
  sliderInput('dts', 'Select date range (days of year)', min = 1, max = 365, value = c(1, 365))
)
column(12, 
  radioButtons('day', label = h3('Day'), choices = list('one' = 1, 'three' = 3, 'six' = 6, 'nine' = 9, 'twelve' = 12))
)
column(12, 
  radioButtons('hour', label = h3('Hour'), choices = list('one' = 1, 'three' = 3, 'six' = 6, 'nine' = 9, 'twelve' = 12))
)
column(12,
  radioButtons('tide', label = h3('Tidal range'), choices = c(0.2, 0.4, 0.6, 0.8, 1))
)
```

Row {.tabset}
-------------------------------------

### Correlation plots

```{r}
output$corplo <- renderPlot(corplo())#, height = 300, width = 900)
plotOutput('corplo')
```

### Correlation summary

```{r}
output$cortab <- renderTable(cortab())
tableOutput('cortab')
```

### $\beta_2$ plot

```{r}
output$betplo <- renderPlot(betplo())
plotOutput('betplo')
```

Row {.tabset}
-------------------------------------

### Metabolism plots

```{r}
output$metplo <- renderPlot(metplo())#, height = 600, width = 900)
plotOutput('metplo')
```

### Dissolved oxygen and tidal height

```{r}
output$dotdplo <- renderPlot(dotdplo())#, height = 600, width = 900)
plotOutput('dotdplo')
```

### Anomaly

```{r}
output$anotab <- renderTable(anotab())
tableOutput('anotab')
```


